/** Découverte variée — mot-clé tiré au hasard (liste générale) */
export const TRENDING_KEYWORDS_GENERAL = [
  // Musique & Culture
  'hits 2026',
  'top musique 2026 francais',
  'nouveaux artistes francais 2026',
  'rap francais 2026',
  'concert live francais',
  
  // Viral & Tendances
  'viral this week francais',
  'trending france',
  'buzz du moment francais',
  'meme francais 2026',
  'tiktok compilation francais',
  
  // Cinéma & Séries
  'short film francais',
  'film entier en francais',
  'bande annonce vf 2026',
  'critique film francais',
  'analyse série francais',
  
  // Documentaires & Reportages
  'documentary francais',
  'reportage France francais',
  'investigation francais',
  'documentaire nature francais',
  'reportage société francais 2026',
  
  // Tech & Innovation
  'tech review francais',
  'test high tech francais',
  'nouveauté tech 2026 francais',
  'smartphone test francais',
  'IA actualité francais 2026',
  
  // Gaming
  'gaming highlights francais',
  'clash royale francais',
  'gameplay francais 2026',
  'let\'s play francais',
  'esport france',
  'gaming news francais',
  
  // Cuisine & Lifestyle
  'cooking recipe',
  'recette facile francais',
  'chef cuisine francais',
  'street food france',
  
  // Science & Éducation
  'science explained francais',
  'vulgarisation scientifique francais',
  'TED talk français',
  'deep dive explained francais',
  'c\'est pas sorcier',
  
  // Humour & Divertissement
  'comedy sketch francais',
  'sketch humour français',
  'stand up francais 2026',
  'parodie francais',
  'best of humour francais',
  
  // Voyage & Aventure
  'travel vlog francais',
  'voyage france 2026',
  'roadtrip francais',
  'backpacking francais',
  'vanlife',
  'autonomie francais',
  'permaculture francais',
  
  // Sport & Fitness
  'workout motivation francais',
  'musculation francais',
  'coaching sport francais',
  'yoga francais',
  
  // Créateurs & Behind the Scenes
  'making of',
  'behind the scenes francais',
  'doc nozman francais',
  'squeezie',
  'mcfly et carlito',
  'le rire jaune',
  'cyprien',
  'norman',
  'joueur du grenier',
  'e-pensé',
  'idriss aberkane',
  'revue du monde',
  'poisson fécond',
  // Gaming & Divertissement (10M+)
  'squeezie',
  'gotaga',
  'michou',
  'inoxtag',
  
  // Humour & Sketches (5M+)
  'cyprien',
  'norman fait des vidéos',
  'natoo',
  'mcfly et carlito',
  'le rire jaune',
  'amixem',
  'fastgoodcuisine',
  
  // Gaming & Let's Play
  'joueur du grenier',
  'xari',
  'domingo',
  'lebouseuh',
  'fuze iii',
  'maghla',
  'joyca',
  
  // Lifestyle & Vlogs
  'enjoyphoenix',
  'sananas',
  'lena situations',
  'just riadh',
  'lebouseuh',
  
  // Tech & Science
  'doc seven',
  'poisson fécond',
  'une baguette',
  'dirty biology',
  'science étonnante',
  'nota bene',
  
  // Musique & Rap
  'squeezie gaming',
  'seb la frite',
  'tim',
  'mister v',
  'domingo',
  
  // Cinéma & Critique
  'le fossoyeur de films',
  'durendal',
  'chroma',
  'crossed',
  
  // Sport & Aventure
  'tibo inshape',
  'terrafrost',
  'hugo décrypte',
  
  // Cuisine
  'chef michel dumas',
  'fastgoodcuisine',
  'la petite bette',
  
  // Éducation & Vulgarisation
  'e-penser',
  'chat sceptique',
  'dans ton corps',
  'max bird',
  'linguisticae',
  
  // Inclassables & Multi-formats
  'jimmy fait l\'con',
  'la ferme jérôme',
  'superconnerie',
  'georges',
  'cilabus',
  'exclarrogatif',
  'les freres poulain',
  'le journal de l \'espace',
  
  
  // Podcasts & Interviews
  'podcast interview francais',
  'podcast actualité francais 2026',
  'interview exclusive francais',
  
  // Animation & Créatif
  'animation short francais',
  'motion design francais',
  'court métrage animation',
  
  // Dev & Code (ton domaine)
  'nouveauté css 2026 francais',
  'nouveauté html 2026 francais',
  'nouveauté javascript 2026 francais',
  'nouveauté svelte 2026 francais',
  'tuto dev web francais 2026',
  'fullstack tutorial francais',
  'node.js francais 2026',
  
  // Cybersécurité
  'sécurité informatique',
  'cybersecurity français',
  'cybersecurity en français',
  'cybersecurity en français 2026',
  'hacking ethique francais',
  'pentesting francais',
  
  // Formats spécifiques
  'reaction video francais',
  'défi challenge francais',
  'vlog quotidien francais',
  'asmr francais',
  'unboxing francais 2026',
];

export const TRENDING_KEYWORDS_MUSIC = [
  'clip officiel',
  'nouveautés musique 2026',
  'live acoustique',
  'remix viral',
  'jazz lounge',
  'hip hop francophone',
  'rock live session',
  'deep house mix',
  'chanson française 2026',
  'acoustic cover',
  'classical piano relax',
  'pop hits 2026',
  'indie music 2026',
  'festival live music',
  'slow jam R&B',
  'electro français',

  // divers
   "0 vue",
"1 vue",
"2 vues",
"aucune vue",
"moins de 10 vues",
"moins de 100 vues",
"petit créateur",
"créateur inconnu",
"chaîne inconnue",
"nouveau youtubeur",
"nouvelle chaîne",
"chaîne émergente",
"contenu rare",
"vidéo rare",
"archive oubliée",
"vidéo supprimée",
"reupload",
"upload oublié",
"pépite cachée",
"underground",
"introuvable",
"non listé",
"version rare",
"édition rare",
"demo",
"démo",
"prototype",
"beta",
"bêta",
"test",
"fuite",
"leak",
"enregistrement amateur",
"caméra cachée",
"captation",
"vhs",
"cassette",
"rip cassette",
"rip tv",
"rip radio",
"enregistrement tv",
"enregistrement radio",
"old school",
"vintage",
"nostalgie",
"archives",
"archive tv",
"archive radio",
"vidéo amateur",
"clip amateur",
"freestyle",
"session studio",
"session live",
"live inédit",
"concert rare",
"interview rare",
"making of",
"behind the scenes",
"coulisses",
"version longue",
"director cut",
"cut alternatif",
"bootleg",
"fan edit",
"fan made",
"non officiel",
"inédit",
"jamais vu",
"perdu",
"lost media",
"media perdu",
"vidéo oubliée",
"contenu oublié",
"deep youtube",
"deep web youtube",
"youtube caché",
"algorithme cassé",
"recommandation étrange",
"rabbit hole",
"obscur",
"bizarre",
"étrange",
"malaisant",
"weird french youtube",
"glitch",
"bug",
"erreur",
"camcorder",
"film amateur",
"court métrage amateur",
"ovni",
"paranormal",
"mystère",
"étrange vidéo",
"creepy",
"cringe",
"drôle",
"fail",
"compilation rare",
"musique rare",
"mix rare",
"dj underground",
"techno underground",
"rap underground",
"maquette rap",
"instrumental rare",
"sample rare",
"cassette audio",
"vinyle rare",
"youtube france",
"youtube fr",
"francophone",
"tendance",
"trend",
"viral",
"buzz",
"explosion de vues",
"vidéo montante",
"en hausse",
"algorithme",
"pour toi",
"fyp",
"recommandé",
"nouveau trend",
"trend france",
"trend tiktok",
"trend youtube",
"mème",
"meme",
"shitpost",
"shitposting",
"ia",
"intelligence artificielle",
"ai generated",
"loop",
"speed up",
"slowed",
"phonk",
"edit anime",
"dark edit",
"sigma",
"motivation",
"drama",
"iceberg",
"thread horreur",
"histoire vraie",
"urbex",
"caméra surveillance",
"dashcam",
"bodycam",
"live",
"stream",
"stream replay",
"petit streamer",
"stream oublié",
"gaming inconnu",
"jeu oublié",
"jeu abandonné",
"mod rare",
"serveur privé",
"serveur fermé",
"version alpha",
"youtube algorithm",
"viral français",
"vidéo sous cotée",
"sous estimé",
"hidden gem",
"trésor caché",
"artiste inconnu",
"musicien inconnu",
"rappeur inconnu",
"youtube expérimental",
"édition fan",
"documentaire amateur",
"forum archive",
"internet ancien",
"web 2000",
"skyblog",
"dailymotion archive",
"forum perdu",
"ancienne vidéo",
"vidéo 2006",
"vidéo 2007",
"vidéo 2008",
"vidéo 2009",
"vidéo 2010",
"qualité 240p",
"qualité 144p",
"micro chaîne",
"micro influenceur",
"créateur émergent",
"vidéo sans commentaire",
"ambiance",
"asmr amateur",
"ambiance pluie",
"ville nocturne",
"exploration urbaine",
"caméra fixe",
"caméra cachée",
"captation",
"vhs",
"cassette",
"rip cassette",
"rip tv",
"rip radio",
"enregistrement tv",
"enregistrement radio",
"timelapse amateur",
"curionautes des sciences",
"Ludikids"

];

export function pickTrendingKeyword(musicOnly) {
  const list = musicOnly ? TRENDING_KEYWORDS_MUSIC : TRENDING_KEYWORDS_GENERAL;
  return list[Math.floor(Math.random() * list.length)];
}
